/*
 * This source file was generated by the Gradle 'init' task
 */
package cursotdd;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {
    Pilha p;
    @BeforeEach
    public void setUp() {
        p = new Pilha(10);
    }

    @Test void pilhaVazia() {
        assertTrue(p.estaVazia());
        assertEquals(0, p.tamanho());
    }
    @Test void empilhaUm() {
        p.empilha(1);
        assertFalse(p.estaVazia()); 
        assertEquals(1, p.tamanho());
        assertEquals(1, p.topo());
    }
    @Test void empilhaEDesempilha() {
        p.empilha(1);
        p.empilha(2);
        assertEquals(2, p.tamanho());
        assertEquals(2, p.topo());
        p.desempilha();
        assertEquals(1, p.tamanho());
        assertEquals(1, p.topo());
    }

    @Test
    public void removeDaPilhaVazia(){
        assertThrows(PilhaVaziaException.class,  p::desempilha);
        assertTrue(p.estaVazia());
    }

    @Test
    public void entopePilha(){
        for(int i = 0; i < 10; i++){
            p.empilha(i);
        }
        try{
            p.empilha(2);
            fail();
        }
        catch(PilhaCheiaException e){
            assertEquals("Pilha cheia", e.getMessage());
        }
    }
}
